//複数のページで共有される。再レンダリングされない。
import type { Metadata } from "next";
//TODO:googleフォントは環境に依存しない。商用利用可能なので採用。
// import { Geist, Geist_Mono } from "next/font/google";
import { Geist } from 'next/font/google'
const geist = Geist({
  subsets: ['latin'],
})
//TODO:グローバルはここに切ってるんだね
import "./globals.css";

//TODO:
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

//TODO:
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  //TODO:タイトルと説明。タイトル個別に変える場合は、個別画面でmetadata定義。<HEAD>に入れたいものを定義
  title: "remindreact",
  description: "reactのリマインド。３年前からずいぶん変わってる。。。",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //TODO:    <html lang="en">
    <html lang="ja">      
      {
      //TODO:<HEAD>がないが、上記Metadataから生成されるらしい
      //TODO:reactのコメントは{}内//
      //<body className={`${geistSans.variable} ${geistMono.variable}`}>
      }
      <body className={geist.className}>
        {children}
      </body>
    </html>
  );
}
